"""Stage 2, GRPO with verifiable rewards: optimize for verified correct answers.

Starts from the merged SFT model and trains a fresh LoRA adapter. The reward is the
LedgerMind verifier (``ledgermind.rewards``); there is no reward model. With
``use_vllm: true`` rollouts are generated by vLLM inside the training loop, which is
where most of GRPO's compute goes.

Usage::

    uv run python training/grpo.py --config training/configs/grpo_qwen3_4b.yaml
"""

from __future__ import annotations

import argparse
import json

from common import (
    fits,
    install_cpu_kernel_fallback,
    last_checkpoint,
    load_config,
    load_tokenizer,
    write_run_metadata,
)
from datasets import Dataset
from peft import LoraConfig
from trl import GRPOConfig, GRPOTrainer

from ledgermind.data.prepare import read_jsonl
from ledgermind.rewards import RewardWeights
from ledgermind.training.records import grpo_record
from ledgermind.training.reward_fn import make_reward_fn


def build_dataset(cfg: dict, tokenizer) -> Dataset:
    records = [grpo_record(ex) for ex in read_jsonl(cfg["train_file"])]
    if cfg.get("prompt_ids_file"):
        with open(cfg["prompt_ids_file"]) as fh:
            keep = set(json.load(fh)["informative"])
        records = [r for r in records if r["id"] in keep]
    budget = cfg["max_prompt_length"]
    records = [r for r in records if fits(tokenizer, r["prompt"], "", budget)]
    if cfg.get("max_train_examples"):
        records = records[: cfg["max_train_examples"]]
    return Dataset.from_list(records)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--config", required=True)
    args = parser.parse_args()
    cfg = load_config(args.config)
    if install_cpu_kernel_fallback():
        print("Triton unavailable: using the PyTorch log prob fallback (smoke tests only)")

    tokenizer = load_tokenizer(cfg["model"])
    train = build_dataset(cfg, tokenizer)
    print(f"GRPO prompts: {len(train)}")

    lora = cfg["lora"]
    peft_config = LoraConfig(
        r=lora["rank"],
        lora_alpha=lora["alpha"],
        lora_dropout=lora.get("dropout", 0.0),
        target_modules=lora.get("target_modules", "all-linear"),
        task_type="CAUSAL_LM",
    )
    t = cfg["train"]
    grpo_args = GRPOConfig(
        output_dir=cfg["output_dir"],
        learning_rate=t["learning_rate"],
        lr_scheduler_type=t.get("lr_scheduler_type", "constant_with_warmup"),
        warmup_steps=t.get("warmup", 0.03),
        beta=t.get("beta", 0.0),
        loss_type=t.get("loss_type", "dapo"),
        num_generations=t["num_generations"],
        temperature=t.get("temperature", 0.9),
        max_completion_length=cfg["max_completion_length"],
        mask_truncated_completions=t.get("mask_truncated_completions", True),
        per_device_train_batch_size=t["per_device_batch_size"],
        gradient_accumulation_steps=t["gradient_accumulation_steps"],
        num_train_epochs=t.get("epochs", 1),
        max_steps=t.get("max_steps", -1),
        gradient_checkpointing=t.get("gradient_checkpointing", True),
        bf16=t.get("bf16", True),
        logging_steps=t.get("logging_steps", 5),
        save_steps=t.get("save_steps", 50),
        log_completions=t.get("log_completions", True),
        use_vllm=t.get("use_vllm", False),
        vllm_mode=t.get("vllm_mode", "colocate"),
        vllm_gpu_memory_utilization=t.get("vllm_gpu_memory_utilization", 0.3),
        report_to=t.get("report_to", "none"),
        seed=t.get("seed", 0),
        model_init_kwargs=cfg.get("model_init_kwargs"),
        use_cpu=t.get("use_cpu", False),
    )
    weights = RewardWeights(**cfg.get("reward_weights", {}))
    trainer = GRPOTrainer(
        model=cfg["model"],
        reward_funcs=make_reward_fn(weights, cfg.get("match_mode", "scale")),
        args=grpo_args,
        train_dataset=train,
        processing_class=tokenizer,
        peft_config=peft_config,
    )
    result = trainer.train(resume_from_checkpoint=last_checkpoint(cfg["output_dir"]))
    trainer.save_model(cfg["output_dir"])
    write_run_metadata(
        cfg["output_dir"],
        cfg,
        train_prompts=len(train),
        train_loss=result.training_loss,
        log_history=trainer.state.log_history,
    )


if __name__ == "__main__":
    main()
